package games

import (
	"eman/passport/game/src/models"
	"github.com/globalsign/mgo/bson"
	"math/rand"
)

func getWhatTheFlagQuestions(level *models.Level) func() ([]*models.Question, error) {

	return  func() ([]*models.Question, error) {

		var setup []*models.Question
		for i := 0; i < level.GetNumberOfQuestions(); i++ {
			setup = append(setup, getWhatTheFlagSingleQuestion())
		}

		return setup, nil
	}
}

func getWhatTheFlagSingleQuestion() *models.Question {

	q := models.NewQuestion()

	r := rand.Perm(len(countries))
	correct := r[:1]
	wrong := r[1:4]

	country := countries[correct[0]]
	option := models.QuestionOption{
		bson.NewObjectId(),
		country.Name,
	}

	q.Question = country.Image
	q.Answer = option.Id
	q.Options = append(q.Options, option)

	for _, value := range wrong {
		country = countries[value]
		q.Options = append(q.Options, models.QuestionOption{
			bson.NewObjectId(),
			country.Name,
		})
	}

	rand.Shuffle(len(q.Options), func(i, j int) { q.Options[i], q.Options[j] = q.Options[j], q.Options[i] })

	return q
}

type Country struct {
	Name  string
	Image string
}

var countries = []Country{
	{"Afghanistan", "Afghanistan-flag"},
	{"Aland islands", "Aland-islands-flag"},
	{"Albania", "Albania-flag"},
	{"Algeria", "Algeria-flag"},
	{"American samoa", "American-samoa-flag"},
	{"Andorra", "Andorra-flag"},
	{"Angola", "Angola-flag"},
	{"Anguilla", "Anguilla-flag"},
	{"Antarctica", "Antarctica-flag"},
	{"Antigua and barbuda", "Antigua-and-barbuda-flag"},
	{"Argentina", "Argentina-flag"},
	{"Armenia", "Armenia-flag"},
	{"Aruba", "Aruba-flag"},
	{"Australia", "Australia-flag"},
	{"Austria", "Austria-flag"},
	{"Azerbaijan", "Azerbaijan-flag"},
	{"Bahamas", "Bahamas-flag"},
	{"Bahrain", "Bahrain-flag"},
	{"Bangladesh", "Bangladesh-flag"},
	{"Barbados", "Barbados-flag"},
	{"Belarus", "Belarus-flag"},
	{"Belgium", "Belgium-flag"},
	{"Belize", "Belize-flag"},
	{"Benin", "Benin-flag"},
	{"Bermuda", "Bermuda-flag"},
	{"Bhutan", "Bhutan-flag"},
	{"Biot", "Biot-flag"},
	{"Bolivia", "Bolivia-flag"},
	{"Bonaire", "Bonaire-flag"},
	{"Bosnian", "Bosnian-flag"},
	{"Botswana", "Botswana-flag"},
	{"Bouvet island", "Bouvet-island-flag"},
	{"Brazil", "Brazil-flag"},
	{"British antarctic territory", "British-antarctic-territory-flag"},
	{"British virgin islands", "British-virgin-islands-flag"},
	{"Brunei", "Brunei-flag"},
	{"Bulgaria", "Bulgaria-flag"},
	{"Burkina faso", "Burkina-faso-flag"},
	{"Burma", "Burma-flag"},
	{"Burundi", "Burundi-flag"},
	{"Cambodia", "Cambodia-flag"},
	{"Cameroon", "Cameroon-flag"},
	{"Canada", "Canada-flag"},
	{"Cape verde", "Cape-verde-flag"},
	{"Cascadia", "Cascadia-flag"},
	{"Cayman islands", "Cayman-islands-flag"},
	{"Central African Republic", "Central-African-Republic-flag"},
	{"Chad", "Chad-flag"},
	{"Chile", "Chile-flag"},
	{"China", "China-flag"},
	{"Christmas island", "Christmas-island-flag"},
	{"Cocos islands", "Cocos-islands-flag"},
	{"Colombia", "Colombia-flag"},
	{"Comoros", "Comoros-flag"},
	{"Congo Kinshasa", "Congo-Kinshasa-flag"},
	{"Congo", "Congo-flag"},
	{"Cook islands", "Cook-islands-flag"},
	{"Costa Rica", "Costa-Rica-flag"},
	{"Croatian", "Croatian-flag"},
	{"Cuba", "Cuba-flag"},
	{"Curacao", "Curacao-flag"},
	{"Cyprus", "Cyprus-flag"},
	{"Czech republic", "Czech-republic-flag"},
	{"Denmark", "Denmark-flag"},
	{"Djibouti", "Djibouti-flag"},
	{"Dominica", "Dominica-flag"},
	{"Dominican republic", "Dominican-republic-flag"},
	{"East timor", "East-timor-flag"},
	{"Ecuador", "Ecuador-flag"},
	{"Egypt", "Egypt-flag"},
	{"El salvador", "El-salvador-flag"},
	{"England", "England-flag"},
	{"Equatorial guinea", "Equatorial-guinea-flag"},
	{"Eritrea", "Eritrea-flag"},
	{"Estonia", "Estonia-flag"},
	{"Ethiopia", "Ethiopia-flag"},
	{"European union", "European-union-flag"},
	{"Ex Yugoslavia", "Ex-yugoslavia-flag"},
	{"Falkland islands", "Falkland-islands-flag"},
	{"Faroe islands", "Faroe-islands-flag"},
	{"Fiji", "Fiji-flag"},
	{"Finland", "Finland-flag"},
	{"France", "France-flag"},
	{"French polynesia", "French-polynesia-flag"},
	{"French southern territories", "French-southern-territories-flag"},
	{"Gabon", "Gabon-flag"},
	{"Gambia", "Gambia-flag"},
	{"Georgia", "Georgia-flag"},
	{"Germany", "Germany-flag"},
	{"Ghana", "Ghana-flag"},
	{"Gibraltar", "Gibraltar-flag"},
	{"Greece", "Greece-flag"},
	{"Greenland", "Greenland-flag"},
	{"Grenada", "Grenada-flag"},
	{"Guadeloupe", "Guadeloupe-flag"},
	{"Guam", "Guam-flag"},
	{"Guatemala", "Guatemala-flag"},
	{"Guernsey", "Guernsey-flag"},
	{"Guinea bissau", "Guinea-bissau-flag"},
	{"Guinea", "Guinea-flag"},
	{"Guyana", "Guyana-flag"},
	{"Haiti", "Haiti-flag"},
	{"Holy see", "Holy-see-flag"},
	{"Honduras", "Honduras-flag"},
	{"Hong kong", "Hong-kong-flag"},
	{"Hungary", "Hungary-flag"},
	{"Iceland", "Iceland-flag"},
	{"India", "India-flag"},
	{"Indonesia", "Indonesia-flag"},
	{"Iran", "Iran-flag"},
	{"Iraq", "Iraq-flag"},
	{"Ireland", "Ireland-flag"},
	{"Isle of man", "Isle-of-man-flag"},
	{"Israel", "Israel-flag"},
	{"Italy", "Italy-flag"},
	{"Ivory coast", "Ivory-coast-flag"},
	{"Jamaica", "Jamaica-flag"},
	{"Jan mayen", "Jan-mayen-flag"},
	{"Japan", "Japan-flag"},
	{"Jarvis island", "Jarvis-island-flag"},
	{"Jersey", "Jersey-flag"},
	{"Jordan", "Jordan-flag"},
	{"Kazakhstan", "Kazakhstan-flag"},
	{"Kenya", "Kenya-flag"},
	{"Kiribati", "Kiribati-flag"},
	{"Korea", "Korea-flag"},
	{"Kosovo", "Kosovo-flag"},
	{"Kuwait", "Kuwait-flag"},
	{"Kyrgyzstan", "Kyrgyzstan-flag"},
	{"Laos", "Laos-flag"},
	{"Latvia", "Latvia-flag"},
	{"Lebanon", "Lebanon-flag"},
	{"Lesotho", "Lesotho-flag"},
	{"Liberia", "Liberia-flag"},
	{"Libya", "Libya-flag"},
	{"Liechtenstein", "Liechtenstein-flag"},
	{"Lithuania", "Lithuania-flag"},
	{"Luxembourg", "Luxembourg-flag"},
	{"Macau", "Macau-flag"},
	{"Macedonia", "Macedonia-flag"},
	{"Madagascar", "Madagascar-flag"},
	{"Malawi", "Malawi-flag"},
	{"Malaysia", "Malaysia-flag"},
	{"Maldives", "Maldives-flag"},
	{"Mali", "Mali-flag"},
	{"Malta", "Malta-flag"},
	{"Marshall islands", "Marshall-islands-flag"},
	{"Martinique", "Martinique-flag"},
	{"Mauritania", "Mauritania-flag"},
	{"Mauritius", "Mauritius-flag"},
	{"Mayotte", "Mayotte-flag"},
	{"Mexico", "Mexico-flag"},
	{"Micronesia", "Micronesia-flag"},
	{"Moldova", "Moldova-flag"},
	{"Monaco", "Monaco-flag"},
	{"Mongolia", "Mongolia-flag"},
	{"Montenegro", "Montenegro-flag"},
	{"Montserrat", "Montserrat-flag"},
	{"Morocco", "Morocco-flag"},
	{"Mozambique", "Mozambique-flag"},
	{"Myanmar", "Myanmar-flag"},
	{"Namibia", "Namibia-flag"},
	{"Nauru", "Nauru-flag"},
	{"Nepal", "Nepal-flag"},
	{"Netherlands antilles", "Netherlands-antilles-flag"},
	{"Netherlands", "Netherlands-flag"},
	{"New caledonia", "New-caledonia-flag"},
	{"New zealand", "New-zealand-flag"},
	{"Nicaragua", "Nicaragua-flag"},
	{"Niger", "Niger-flag"},
	{"Nigeria", "Nigeria-flag"},
	{"Niue", "Niue-flag"},
	{"Norfolk island", "Norfolk-island-flag"},
	{"North korea", "North-korea-flag"},
	{"Northern ireland", "Northern-ireland-flag"},
	{"Northern mariana islands", "Northern-mariana-islands-flag"},
	{"Norway", "Norway-flag"},
	{"Oman", "Oman-flag"},
	{"Pakistan", "Pakistan-flag"},
	{"Palau", "Palau-flag"},
	{"Palestinian territory", "Palestinian-territory-flag"},
	{"Panama", "Panama-flag"},
	{"Papua new guinea", "Papua-new-guinea-flag"},
	{"Paraguay", "Paraguay-flag"},
	{"Peru", "Peru-flag"},
	{"Philippines", "Philippines-flag"},
	{"Pitcairn", "Pitcairn-flag"},
	{"Poland", "Poland-flag"},
	{"Portugal", "Portugal-flag"},
	{"Puerto Rico", "Puerto-rico-flag"},
	{"Qatar", "Qatar-flag"},
	{"Reunion", "Reunion-flag"},
	{"Romania", "Romania-flag"},
	{"Russia", "Russia-flag"},
	{"Rwanda", "Rwanda-flag"},
	{"Saint Vincent and the Grenadines", "Saint-Vincent-and-the-Grenadines-flag"},
	{"Saint barthelemy", "Saint-barthelemy-flag"},
	{"Saint helena and dependencies", "Saint-helena-and-dependencies-flag"},
	{"Saint helena", "Saint-helena-flag"},
	{"Saint kitts and nevis", "Saint-kitts-and-nevis-flag"},
	{"Saint lucia", "Saint-lucia-flag"},
	{"Saint martin", "Saint-martin-flag"},
	{"Saint pierre and miquelon", "Saint-pierre-and-miquelon-flag"},
	{"Samoa", "Samoa-flag"},
	{"San marino", "San-marino-flag"},
	{"Sao tome and principe", "Sao-tome-and-principe-flag"},
	{"Saudi Arabia", "Saudi-arabia-flag"},
	{"Scotland", "Scotland-flag"},
	{"Senegal", "Senegal-flag"},
	{"Serbia", "Serbia-flag"},
	{"Seychelles", "Seychelles-flag"},
	{"Sierra Leone", "Sierra-leone-flag"},
	{"Singapore", "Singapore-flag"},
	{"Sint Maarten", "Sint-Maarten-flag"},
	{"Sint Eustatius", "Sint-eustatius-flag"},
	{"Slovakia", "Slovakia-flag"},
	{"Slovenia", "Slovenia-flag"},
	{"Solomon islands", "Solomon-islands-flag"},
	{"Somalia", "Somalia-flag"},
	{"South Africa", "South-africa-flag"},
	{"South Georgia", "South-georgia-flag"},
	{"South Sudan", "South-sudan-flag"},
	{"Sovereign Military Order of Malta", "Sovereign-Military-Order-of-Malta-flag"},
	{"Soviet Union", "Soviet-Union-flag"},
	{"Spain", "Spain-flag"},
	{"Sri lanka", "Sri-lanka-flag"},
	{"Sudan", "Sudan-flag"},
	{"Suriname", "Suriname-flag"},
	{"Svalbard", "Svalbard-flag"},
	{"Swaziland", "Swaziland-flag"},
	{"Sweden", "Sweden-flag"},
	{"Switzerland", "Switzerland-flag"},
	{"Syria", "Syria-flag"},
	{"Taiwan", "Taiwan-flag"},
	{"Tajikistan", "Tajikistan-flag"},
	{"Tanzania", "Tanzania-flag"},
	{"Thailand", "Thailand-flag"},
	{"Timor leste", "Timor-leste-flag"},
	{"Togo", "Togo-flag"},
	{"Tokelau", "Tokelau-flag"},
	{"Tonga", "Tonga-flag"},
	{"Trinidad and Tobago", "Trinidad-and-tobago-flag"},
	{"Tunisia", "Tunisia-flag"},
	{"Turkey", "Turkey-flag"},
	{"Turkmenistan", "Turkmenistan-flag"},
	{"Turks and caicos islands", "Turks-and-caicos-islands-flag"},
	{"Tuvalu", "Tuvalu-flag"},
	{"Uganda", "Uganda-flag"},
	{"Ukraine", "Ukraine-flag"},
	{"United arab emirates", "United-arab-emirates-flag"},
	{"United kingdom", "United-kingdom-flag"},
	{"United states", "United-states-flag"},
	{"Uruguay", "Uruguay-flag"},
	{"Uzbekistan", "Uzbekistan-flag"},
	{"Vanuatu", "Vanuatu-flag"},
	{"Vatican city", "Vatican-city-flag"},
	{"Venezuela", "Venezuela-flag"},
	{"Vietnam", "Vietnam-flag"},
	{"Virgin islands", "Virgin-islands-flag"},
	{"Wales", "Wales-flag"},
	{"Wallis and futuna", "Wallis-and-futuna-flag"},
	{"Western sahara", "Western-sahara-flag"},
	{"Yemen", "Yemen-flag"},
	{"Yugoslavia", "Yugoslavia-flag"},
	{"Zambia", "Zambia-flag"},
	{"Zimbabwe", "Zimbabwe-flag"},
}
